[package]
name = "rand_set"
version = "0.1.0"
edition = "2024"
description = "A hash set with O(1) random element access and all standard set operations"
license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.9.1"
